<?xml version="1.0"?>
<robot name="originbot"
    xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- 大号机器人模型 -->
    <!-- PROPERTY LIST -->
    <xacro:property name="M_PI" value="3.1415926" />
    <xacro:property name="base_mass" value="2" />

    <xacro:property name="base_width" value="0.320" />
    <xacro:property name="base_length" value="0.320" />
    <xacro:property name="base_height" value="0.1" />

    <!-- 轮子 -->
    <xacro:property name="wheel_mass" value="0.4" />
    <xacro:property name="wheel_radius" value="0.065" />
    <xacro:property name="wheel_length" value="0.050" />

    <xacro:property name="wheel_joint_x" value="0.14" />
    <xacro:property name="wheel_joint_y" value="0.38" />
    <xacro:property name="wheel_joint_z" value="0.035" />

    <!-- 支撑轮 -->
    <xacro:property name="caster_mass" value="0.4" />
    <xacro:property name="caster_radius" value="0.0267" />
    <xacro:property name="caster_joint_x" value="0.14" />

    <material name="yellow">
        <color rgba="1 0.4 0 1" />
    </material>
    <material name="black">
        <color rgba="0 0 0 0.95" />
    </material>
    <material name="gray">
        <color rgba="0.75 0.75 0.75 1" />
    </material>

    <!-- Macro for inertia matrix -->

    <!-- 球面惯性矩阵 -->
    <xacro:macro name="sphere_inertial_matrix" params="m r">
        <inertial>
            <mass value="${m}" />
            <inertia ixx="${2*m*r*r/5}" ixy="0" ixz="0" iyy="${2*m*r*r/5}" iyz="0"
                izz="${2*m*r*r/5}" />
        </inertial>
    </xacro:macro>

    <!-- 圆柱惯性矩阵 -->
    <xacro:macro name="cylinder_inertial_matrix" params="m r h">
        <inertial>
            <mass value="${m}" />
            <inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0" ixz="0" iyy="${m*(3*r*r+h*h)/12}" iyz="0"
                izz="${m*r*r/2}" />
        </inertial>
    </xacro:macro>

    <!-- 方块惯性矩阵 -->
    <xacro:macro name="box_inertial_matrix" params="m l w h">
        <inertial>
            <mass value="${m}" />
            <inertia ixx="${m*(h*h + l*l)/12}" ixy="0" ixz="0" iyy="${m*(w*w + l*l)/12}" iyz="0"
                izz="${m*(w*w + h*h)/12}" />
        </inertial>
    </xacro:macro>

    <!-- Macro for robot 轮子 -->
    <xacro:macro name="wheel" params="prefix reflect">
        <joint name="${prefix}_wheel_joint" type="continuous">
            <origin xyz="${wheel_joint_x} ${reflect*(base_width+wheel_length)/2} ${-wheel_joint_z}"
                rpy="0 0 0" />
            <parent link="base_link" />
            <child link="${prefix}_wheel_link" />
            <axis xyz="0 1 0" />
        </joint>

        <link name="${prefix}_wheel_link">
            <visual>
                <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <material name="gray" />
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
            </collision>
            <xacro:cylinder_inertial_matrix m="${wheel_mass}" r="${wheel_radius}"
                h="${wheel_length}" />
        </link>

    </xacro:macro>

    <!-- Macro for robot 支撑轮 -->
    <xacro:macro name="caster" params="prefix reflect">
        <joint name="${prefix}_caster_joint" type="fixed">
            <origin xyz="${reflect*caster_joint_x} 0 ${-(base_height/2 + caster_radius)}"
                rpy="0 0 0" />
            <parent link="base_link" />
            <child link="${prefix}_caster_link" />
        </joint>

        <link name="${prefix}_caster_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <sphere radius="${caster_radius}" />
                </geometry>
                <material name="black" />
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <sphere radius="${caster_radius}" />
                </geometry>
            </collision>
            <xacro:sphere_inertial_matrix m="${caster_mass}" r="${caster_radius}" />
        </link>

    </xacro:macro>


    <link name="base_footprint">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.001 0.001 0.001" />
            </geometry>
        </visual>
    </link>

    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 ${base_height/2 + caster_radius*2}" rpy="0 0 0" />
        <parent link="base_footprint" />
        <child link="base_link" />
    </joint>

    <link name="base_link">
        <visual>
            <origin xyz=" 0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <material name="yellow" />
        </visual>
        <collision>
            <origin xyz=" 0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
        </collision>
        <xacro:box_inertial_matrix m="${base_mass}" l="${base_length}" w="${base_width}"
            h="${base_height}" />
    </link>


    <xacro:wheel prefix="left" reflect="1" />
    <xacro:wheel prefix="right" reflect="-1" />

    <xacro:caster prefix="back" reflect="-1" />


</robot>