<?xml version="1.0"?>
<robot name="six_arm" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find mybot_description)/urdf/large_base.xacro" />

    <!-- Transmission is important to link the joints and the controller -->
    <xacro:macro name="wheel_transmission" params="prefix">
        <transmission name="${prefix}_wheel_joint_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${prefix}_wheel_joint">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="${prefix}_wheel_joint_motor">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

        <gazebo reference="${prefix}_wheel_link">
            <material>Gazebo/Gray</material>
            <mu1>100000.0</mu1>
            <mu2>100000.0</mu2>
        </gazebo>
    </xacro:macro>

    <!-- /////////////////////////////////   Gazebo   ////////////////////////////////////// -->
    <gazebo reference="base_footprint">
        <turnGravityOff>false</turnGravityOff>
    </gazebo>
    <gazebo reference="base_link">
        <material>Gazebo/Blue</material>
    </gazebo>

    <gazebo reference="back_caster_link">
        <material>Gazebo/Black</material>
    </gazebo>

    <xacro:wheel_transmission prefix="left" />
    <xacro:wheel_transmission prefix="right" />


    <!-- controller -->
    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <update_rate>30</update_rate>
            <left_joint>left_wheel_joint</left_joint>
            <right_joint>right_wheel_joint</right_joint>
            <wheel_separation>${wheel_joint_y*2}</wheel_separation>
            <wheel_diameter>${2*wheel_radius}</wheel_diameter>
            <max_wheel_torque>10</max_wheel_torque>
            <max_wheel_acceleration>1.0</max_wheel_acceleration>
            <command_topic>cmd_vel</command_topic>
            <publish_odom>true</publish_odom>
            <publish_odom_tf>true</publish_odom_tf>
            <publish_wheel_tf>true</publish_wheel_tf>
            <odometry_topic>odom</odometry_topic>
            <odometry_frame>odom</odometry_frame>
            <robot_base_frame>base_footprint</robot_base_frame>
            <odometry_source>1</odometry_source>
        </plugin>
    </gazebo>
</robot>