<?xml version="1.0"?>
<robot name="six_arm"
    xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find mybot_description)/urdf/large_base.xacro" />
    <xacro:include filename="$(find mybot_description)/urdf/arm.xacro" />

    <!-- arm -->
    <xacro:property name="arm_offset_x" value="0.0" />
    <xacro:property name="arm_offset_y" value="0" />
    <xacro:property name="arm_offset_z" value="${base_height/2+0.01}" />

    <joint name="connect_joint" type="fixed">
        <origin xyz="${arm_offset_x} ${arm_offset_y} ${arm_offset_z}" rpy=" 0 0 0" />
        <parent link="base_link" />
        <child link="arm_base_link" />
    </joint>

    <!-- /////////////////////////////////   Gazebo   ////////////////////////////////////// -->
    <!-- /////////////////////////////////   机械臂   ////////////////////////////////////// -->
    <gazebo reference="arm_base_link">
        <material>Gazebo/White</material>
    </gazebo>
    <gazebo reference="link1">
        <material>Gazebo/Blue</material>
    </gazebo>
    <gazebo reference="link2">
        <material>Gazebo/White</material>
    </gazebo>
    <gazebo reference="link3">
        <material>Gazebo/Blue</material>
    </gazebo>
    <gazebo reference="link4">
        <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="link5">
        <material>Gazebo/White</material>
    </gazebo>
    <gazebo reference="link6">
        <material>Gazebo/Blue</material>
    </gazebo>
    <gazebo reference="gripper_finger_link1">
        <material>Gazebo/White</material>
    </gazebo>
    <gazebo reference="gripper_finger_link2">
        <material>Gazebo/White</material>
    </gazebo>
    
    <xacro:macro name="ros2_control_joint" params="joint_name">
        <joint name="${joint_name}">
            <command_interface name="position">
                <param name="min">-1</param>
                <param name="max">1</param>
            </command_interface>
            <state_interface name="position">
                <param name="initial_value">0.0</param>
            </state_interface>
            <state_interface name="velocity" />
        </joint>
    </xacro:macro>

    <ros2_control name="GazeboSystem" type="system">
        <hardware>
            <plugin>gazebo_ros2_control/GazeboSystem</plugin>
        </hardware>
        <xacro:ros2_control_joint joint_name="joint1" />
        <xacro:ros2_control_joint joint_name="joint2" />
        <xacro:ros2_control_joint joint_name="joint3" />
        <xacro:ros2_control_joint joint_name="joint4" />
        <xacro:ros2_control_joint joint_name="joint5" />
        <xacro:ros2_control_joint joint_name="joint6" />
        <xacro:ros2_control_joint joint_name="finger_joint1" />
    </ros2_control>

    <gazebo>
        <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
            <parameters>$(find mybotp)/config/ros2_controllers.yaml</parameters>
            <robot_param_node>robot_state_publisher</robot_param_node>
        </plugin>
    </gazebo>

    <!-- /////////////////////////////////   底盘   ////////////////////////////////////// -->
    <gazebo reference="base_footprint">
        <turnGravityOff>false</turnGravityOff>
    </gazebo>
    <gazebo reference="base_link">
        <material>Gazebo/Blue</material>
    </gazebo>

    <gazebo reference="back_caster_link">
        <material>Gazebo/Black</material>
    </gazebo>


    <xacro:macro name="wheel_transmission" params="prefix">
        <transmission name="${prefix}_wheel_joint_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${prefix}_wheel_joint">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="${prefix}_wheel_joint_motor">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

        <gazebo reference="${prefix}_wheel_link">
            <material>Gazebo/Gray</material>
            <mu1>100000.0</mu1>
            <mu2>100000.0</mu2>
        </gazebo>
    </xacro:macro>
    
    <xacro:wheel_transmission prefix="left" />
    <xacro:wheel_transmission prefix="right" />

    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <update_rate>30</update_rate>
            <left_joint>left_wheel_joint</left_joint>
            <right_joint>right_wheel_joint</right_joint>
            <wheel_separation>${wheel_joint_y*2}</wheel_separation>
            <wheel_diameter>${2*wheel_radius}</wheel_diameter>
            <max_wheel_torque>10</max_wheel_torque>
            <max_wheel_acceleration>1.0</max_wheel_acceleration>
            <command_topic>cmd_vel</command_topic>
            <publish_odom>true</publish_odom>
            <publish_odom_tf>true</publish_odom_tf>
            <publish_wheel_tf>true</publish_wheel_tf>
            <odometry_topic>odom</odometry_topic>
            <odometry_frame>odom</odometry_frame>
            <robot_base_frame>base_footprint</robot_base_frame>
            <odometry_source>1</odometry_source>
        </plugin>
    </gazebo>
</robot>